export default {
  CREATE_SUPERHERO: 'CREATE_HERO',
  CREATE_SUPERHERO_SUCCESS: 'CREATE_HERO_SUCCESS',

  GET_SUPERHERO: 'GET_SUPERHERO',
  GET_SUPERHERO_SUCCESS: 'GET_SUPERHERO_SUCCESS',

  GET_SUPERHEROES: 'GET_SUPERHEROES',
  GET_SUPERHEROES_SUCCESS: 'GET_SUPERHEROES_SUCCESS',

  UPDATE_SUPERHERO: 'UPDATE_SUPERHERO',
  UPDATE_SUPERHERO_SUCCESS: 'UPDATE_SUPERHERO_SUCCESS',

  DELETE_SUPERHERO: 'DELETE_SUPERHERO',
  DELETE_SUPERHERO_REQUEST: 'DELETE_SUPERHERO_REQUEST',
  DELETE_SUPERHERO_SUCCESS: 'DELETE_SUPERHERO_SUCCESS',
  DELETE_SUPERHERO_ERROR: 'DELETE_SUPERHERO_ERROR',

  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
  SUPERHEROES_REQUEST: 'SUPERHEROES_REQUEST',
  SUPERHEROES_REQUEST_ERROR: 'SUPERHEROES_REQUEST_ERROR',
  CHANGE_HERO_INFO_MODE: 'CHANGE_HERO_INFO_MODE',
};
